spring:
  datasource:
    url: jdbc:h2:mem:dynamic_quartz
    username: rex
    password: 1
    initialization-mode: always
    sql-script-encoding: utf-8
    schema: classpath:static/tables.sql
    data: classpath:static/job.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
